# Generated by Django 2.0.4 on 2018-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('details', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('remain', models.IntegerField()),
            ],
        ),
    ]
